### ISSUE TITLE
Mip Mapping still uses vanilla method while mod is installed

### ISSUE THREAD

**Issue by ShyloFluff** [Permdog99/Legacy-Mipmaps#1]
When using the mod on singleplayer worlds it has no visual effect in-game. 

Fabric Loader: 0.15.10-1.20.4

Mods installed: "fabric-api-0.96.11+1.20.4.jar" and "legacy-mipmaps-1.0.0.jar"

**Comment by Permdog99** [comment]
Make sure your mipmapping in game is not set to 0.

**Comment by ShyloFluff** [comment]
It's set to "Mipmap Levels 4"

**Comment by Permdog99** [comment]
Could you send an image?

**Comment by ShyloFluff** [comment]
![image](https://github.com/Permdog99/Legacy-Mipmaps/assets/61952248/a518c1ac-2a06-4137-8aab-b6e609e249e4)

**Comment by Permdog99** [comment]
Could you send an image within a singleplayer world?

**Comment by ShyloFluff** [comment]
![image](https://github.com/Permdog99/Legacy-Mipmaps/assets/61952248/1f110dcf-b314-4a98-b401-4be5d86d6065)

**Comment by Permdog99** [comment]
Make sure you have the mod installed correctly

**Comment by ShyloFluff** [comment]
It's located in the "mods" folder inside .minecraft

**Comment by Permdog99** [comment]
Don't use the vanilla launcher as it tends to have issues with mods

**Comment by ShyloFluff** [comment]
Every other mod I have installed in the mods folder had worked just fine, I have never had an issue like this. Seems oddly specific that this mod could allegedly require a third party launcher. I think it may be an issue or mistake in the uploaded process probably.

**Comment by Permdog99** [comment]
I have had many people test this mod and it works fine for them. I've tested it myself countless times. There don't seem to be anything wrong with the code or Modrinth. The last thing you should try is to make sure the mod shows up in Mod Menu.

**Comment by ShyloFluff** [comment]
It does show up in modmenu

**Comment by Permdog99** [comment]
Send an image

**Comment by ShyloFluff** [comment]
Maybe its incompatible with certain devices, i'm using intel integrated graphics. I'll send an image.

**Comment by ShyloFluff** [comment]
![image](https://github.com/Permdog99/Legacy-Mipmaps/assets/61952248/cf402605-ed5b-4bc7-9f3a-3f0fad22f96f)

**Comment by ShyloFluff** [comment]
![image](https://github.com/Permdog99/Legacy-Mipmaps/assets/61952248/e325f8e3-39bd-4ca4-a0b3-68d8d5d0867a)

**Comment by ShyloFluff** [comment]
I stripped all the other mods that i had installed when trying to get it working. It only has modmenu and fabric api installed with it

**Comment by Permdog99** [comment]
I will have someone with intel integrated graphics look into it. For now, just wait until I can find the likely cause for this

**Comment by Cixon** [comment]
> I will have someone with intel integrated graphics look into it. For now, just wait until I can find the likely cause for this

ah came for this. btw, thank you for publishing such a neat mod!

**Comment by pewf** [comment]
For some reason I have this issue as well. It was **working for me before** but for some reason now it just has no effect on the game and I've been searching to see if anyone had a similar issue as me and lo and behold. Btw I do not have the same system configuration, I'm on an m2 mac.

**Comment by Permdog99** [comment]
> For some reason I have this issue as well. It was **working for me before** but for some reason now it just has no effect on the game and I've been searching to see if anyone had a similar issue as me and lo and behold. Btw I do not have the same system configuration, I'm on an m2 mac.
> 
> Also I checked and made sure mipmap levels are at 4 and I tried with no mods installed as well

Make sure to go into the settings and select the correct mipmapping type

**Comment by pewf** [comment]
> > For some reason I have this issue as well. It was **working for me before** but for some reason now it just has no effect on the game and I've been searching to see if anyone had a similar issue as me and lo and behold. Btw I do not have the same system configuration, I'm on an m2 mac.
> > Also I checked and made sure mipmap levels are at 4 and I tried with no mods installed as well
> 
> Make sure to go into the settings and select the correct mipmapping type

I carefully made sure to go into the settings and select any mipmapping that wasn't java in the settings and it still showed no results. I'm really not sure why.

![Screenshot 2024-07-27 at 16 59 15](https://github.com/user-attachments/assets/964fc254-34b9-46eb-bada-36807156b69d)

**Comment by Permdog99** [comment]
> > > For some reason I have this issue as well. It was **working for me before** but for some reason now it just has no effect on the game and I've been searching to see if anyone had a similar issue as me and lo and behold. Btw I do not have the same system configuration, I'm on an m2 mac.
> > > Also I checked and made sure mipmap levels are at 4 and I tried with no mods installed as well
> > 
> > 
> > Make sure to go into the settings and select the correct mipmapping type
> 
> I carefully made sure to go into the settings and select any mipmapping that wasn't java in the settings and it still showed no results. I'm really not sure why.
> 
> ![Screenshot 2024-07-27 at 16 59 15](https://private-user-images.githubusercontent.com/78571856/352778935-964fc254-34b9-46eb-bada-36807156b69d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMTc4NjMsIm5iZiI6MTcyMjExNzU2MywicGF0aCI6Ii83ODU3MTg1Ni8zNTI3Nzg5MzUtOTY0ZmMyNTQtMzRiOS00NmViLWJhZGEtMzY4MDcxNTZiNjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDIxNTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODAxMWQxN2VkMzRkMzhjZDMwMDMyMmE4MzFhMmYyZmE4YTY1NTJlMGE2ZTg2NTIyMTJhOTg0MWM4MGM1YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgyvWlx_yO0yolFnxw_Zs7pIhisk5L_Jabn5lyPghoA)

Can you send an image of in-game?

**Comment by pewf** [comment]
> > > > For some reason I have this issue as well. It was **working for me before** but for some reason now it just has no effect on the game and I've been searching to see if anyone had a similar issue as me and lo and behold. Btw I do not have the same system configuration, I'm on an m2 mac.
> > > > Also I checked and made sure mipmap levels are at 4 and I tried with no mods installed as well
> > > 
> > > 
> > > Make sure to go into the settings and select the correct mipmapping type
> > 
> > 
> > I carefully made sure to go into the settings and select any mipmapping that wasn't java in the settings and it still showed no results. I'm really not sure why.
> > ![Screenshot 2024-07-27 at 16 59 15](https://private-user-images.githubusercontent.com/78571856/352778935-964fc254-34b9-46eb-bada-36807156b69d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMTc4NjMsIm5iZiI6MTcyMjExNzU2MywicGF0aCI6Ii83ODU3MTg1Ni8zNTI3Nzg5MzUtOTY0ZmMyNTQtMzRiOS00NmViLWJhZGEtMzY4MDcxNTZiNjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDIxNTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODAxMWQxN2VkMzRkMzhjZDMwMDMyMmE4MzFhMmYyZmE4YTY1NTJlMGE2ZTg2NTIyMTJhOTg0MWM4MGM1YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgyvWlx_yO0yolFnxw_Zs7pIhisk5L_Jabn5lyPghoA)
> 
> Can you send an image of in-game?

Sure here you go
![Screenshot 2024-07-27 at 17 17 25](https://github.com/user-attachments/assets/7d8d2b55-3206-4497-a2eb-0032e45234f8)

**Comment by Permdog99** [comment]
Set your mipmapping to 4 and make sure that any resource packs aren't conflicting with the mipmaps

**Comment by pewf** [comment]
> Set your mipmapping to 4 and make sure that any resource packs aren't conflicting with the mipmaps

I'm happy to say that it started working after I disabled one of my texture packs. How can I make sure a resource pack doesn't conflict with the mipmaps?

**Comment by Permdog99** [comment]
> > Set your mipmapping to 4 and make sure that any resource packs aren't conflicting with the mipmaps
> 
> I'm happy to say that it started working after I disabled one of my texture packs. How can I make sure a resource pack doesn't conflict with the mipmaps?

There is usually a line that the log will spit out saying something like "texture's resolution is too high - setting mipmap level to x". Note that I am paraphrasing here

**Comment by pewf** [comment]
> > > Set your mipmapping to 4 and make sure that any resource packs aren't conflicting with the mipmaps
> > 
> > 
> > I'm happy to say that it started working after I disabled one of my texture packs. How can I make sure a resource pack doesn't conflict with the mipmaps?
> 
> There is usually a line that the log will spit out saying something like "texture's resolution is too high - setting mipmap level to x". Note that I am paraphrasing here

thank you i will try and investigate this using the information youve given me

**Comment by pewf** [comment]
hey bro it seems that the mod Nostalgic Tweaks also conflicts with this mod in some way because I actually tested no resource packs with no mods on and when I enabled all of my mods I saw that the mipmaps stopped working, I suspected nostalgic tweaks of being the mod and disabled it and when I relaunched the game I saw that mipmaps were working again

**Comment by pewf** [comment]
> hey bro it seems that the mod Nostalgic Tweaks also conflicts with this mod in some way because I actually tested no resource packs with no mods on and when I enabled all of my mods I saw that the mipmaps stopped working, I suspected nostalgic tweaks of being the mod and disabled it and when I relaunched the game I saw that mipmaps were working again

follow up on this. it was actually a setting called "disable mipmap texturing" so its my fault haha

**Comment by Cjnator38** [comment]
happened to me too for the same reason LMAO

guessing it was a re-console config update
